# Generated by Django 4.2.3 on 2023-07-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='static/backgroundphotos/')),
                ('hackathon_image', models.ImageField(default='photos/default.png', upload_to='static/hackathonphotos/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('submission_type', models.CharField(choices=[('image', 'image'), ('file', 'file'), ('link', 'link')], default='link', max_length=15)),
                ('reward_prize', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('Summary', models.TextField(blank=True, null=True)),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to='static/submissionphotos/')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='static/submissionfile/')),
                ('submission_link', models.URLField(max_length=128)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackathonApp.hackathontable')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
