# Generated by Django 4.2.3 on 2023-07-14 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontable',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
