# Generated by Django 4.2.3 on 2023-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackathonApp', '0002_submissiontable_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathontable',
            name='hackathon_image',
            field=models.ImageField(default='static/hackathonphotos/default.png', upload_to='static/hackathonphotos/'),
        ),
    ]
